packages:
  - "apps/*"
  - "packages/*"
overrides:
  "@napi-rs/wasm-runtime": "1.1.6"
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
